wiki/encyclopedia/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = 'encyclopedia'

urlpatterns = [
    path("", views.index, name="index"),
    path('newpage/', views.new_page, name = 'newpage'),
    path('wiki/<str:title>', views.entry, name = 'entries'),
    path('wiki/<str:title>/edit',views.edit, name = 'edit'),
    path('search', views.search, name = 'search'),
    path('random', views.random, name = 'random')
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

class Entry(models.Model):
    title = models.CharField(max_length= 30)

wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django import forms 
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView

import urllib.request
from markdown2 import Markdown
import os
from random import randint

from . import models
from . import util

class NewPage(forms.Form):
    title = forms.CharField(label="Title",widget=forms.TextInput(
        attrs={'placeholder': 'Page Title'}))
    content = forms.CharField(label="Content", widget=forms.Textarea(
        attrs={'placeholder': 'Enter new page content here in Markdown format'}))

class EditPage(forms.Form):
    content = forms.CharField(label="Content",required=True, widget=forms.Textarea(
        attrs={'placeholder': 'Edit page\'s content here in Markdown format',
                'required':True,
                }))


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def new_page(request):
    form = NewPage(request.POST)
    if form.is_valid():
        f = open('entries/' + form.cleaned_data['title'] + '.md', 'x')
        f.write(form.cleaned_data['content'])
        f.close()
        return redirect('encyclopedia:index')
    return render(request, './encyclopedia/newpage.html', {
        'form': form
    }
    )

    return render(request, './encyclopedia/newpage.html', {'form': form})

def entry(request,title):
    markdowner = Markdown()
    content = util.get_entry(title)
    if content == None:
        return HttpResponse('Fuck you')
    else:
        content = markdowner.convert(util.get_entry(title))
        return render(request,'encyclopedia/entry.html',{
            'title':title,
            'content':content
        })

def edit(request,title):
    content = util.get_entry(title)
    form = EditPage(request.POST)
    initial = EditPage(initial={'content': content, 'title':title})
    if form.is_valid():
        content = form.cleaned_data['content']  
        util.save_entry(title, content)
        return redirect('encyclopedia:index')

    else:
        content = util.get_entry(title)
        form = EditPage(initial= {'title':title, 'content':content})

    return render(request, './encyclopedia/edit.html', {
        'content': content,
        'title':title,
        'form': form,     
    }
    )

def search(request):   
    counter = 0
    result = set()
    entries = util.list_entries()
    if request.method == 'GET':
        query = request.GET.get('q')    
        if query == '': #If it's nothing
            query = 'NONE'    
        if query in entries:
            return redirect(f'wiki/{query}')
        else:
            results = [entry for entry in entries if query.lower() in entry.lower()]
            return render(request, "encyclopedia/index.html", {
                "entries": results
                })
                   
    return render(request, 'encyclopedia/search.html', {'results':result})

def random(request):
    arr = util.list_entries()
    index = randint(0, len(arr)-1)
    rand = arr[index]
    return HttpResponseRedirect(f'wiki/{rand}')

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{%block title%} 
{{title}}
{% endblock %}
{% block body %}
<h1>Editing a page</h1>
<h1>{{title}}</h1>
<form action = "" method = "POST">
    {% csrf_token %}
    {{form}}
    <input type = "submit" value = 'Save'>
</form>
{% endblock body %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}
{% autoescape on %}
{%block title%} 
    {{title}}
{% endblock %}
{%block body%}

    {{content|safe}} 
    <a href = '{{title}}/edit'>Edit</a>
{%endblock%}

{% endautoescape %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki
{% endblock %}

{% block body %}

    {%if messages%}
    <script>
        {%for i in messages%}
        {%endfor%}
    </script>
    {%endif%}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href = "/wiki/{{entry}}" open>{{ entry }}</a></li>
        {% endfor %} 
    </ul>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action = "{% url 'encyclopedia:search' %}" method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href = "{% url 'encyclopedia:newpage' %}">Create New Page</a>
                </div>
                <div>
                    <a href ="{% url 'encyclopedia:random' %}"">Random Page </a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{%block title%} 

Creating a page
{% endblock %}
{% block body %}
<h1>Creating A New Pages</h1>
<form action = "" method = "post">
    {% csrf_token %}
    {{form}}
    <input type = "submit" value = 'Create'>
</form>
{% endblock body %}

wiki/encyclopedia/templates/encyclopedia/random.html
{% extends 'layout.html' %}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends 'encyclopedia/layout.html' %}

{%block title%}
Search
{% endblock %}

{% block body %}
<h1>Searching Results:</h1>
{% for result in results%}
    <ul>
        <li><a href = "/wiki/{{result}}" open>{{ result }}</a></li>
    </ul>
{% endfor %}
{% endblock %}